### ISSUE TITLE
[Feature] 默认排除方案保存

### ISSUE THREAD

**Issue by byoukinn** [CoCoTeaNet/ElysianAnime#12]
![image](https://github.com/user-attachments/assets/4d8aea0d-dd0e-43f7-83d2-2e8f8a62b04e)
提供保存默认排除方案的方法

**Comment by CoCoTeaNet** [comment]
Completed in [2.2.3](https://github.com/CoCoTeaNet/ElysianAnime/releases/tag/2.2.3)
