### ISSUE TITLE
[Feature] 增加资源解析后的匹配结果预览 

### ISSUE THREAD

**Issue by byoukinn** [CoCoTeaNet/ElysianAnime#13]
![image](https://github.com/user-attachments/assets/5b065404-a083-4456-a796-f6b9b9c2c7cf)

匹配结果预览

**Comment by CoCoTeaNet** [comment]
Completed in [2.2.3](https://github.com/CoCoTeaNet/ElysianAnime/releases/tag/2.2.3)
